In [1]:
import numpy
import pandas
ar = numpy.array([[1.1, 2, 3.3, 4], [2.7, 10, 5.4, 7], [5.3, 9, 1.5, 15]])
df1 = pandas.DataFrame(ar, index = ['a1', 'a2', 'a3'], columns = ['A', 'B', 'C', 'D'])

In [2]:
ar

array([[ 1.1,  2. ,  3.3,  4. ],
       [ 2.7, 10. ,  5.4,  7. ],
       [ 5.3,  9. ,  1.5, 15. ]])

In [11]:
print("anas hamza")
print("anas\thamza")

anas hamza
anas	hamza

In [3]:
print(ar[0,2])

3.3

In [4]:
df1

      A     B    C     D
a1  1.1   2.0  3.3   4.0
a2  2.7  10.0  5.4   7.0
a3  5.3   9.0  1.5  15.0

In [7]:
#print(df1['A'])
print(df1.tail(2))

      A     B    C     D
a2  2.7  10.0  5.4   7.0
a3  5.3   9.0  1.5  15.0

- df.info() : permet d'avoir des infos sur le dataframe (y compris place occupée).
- df.head(2) : renvoie un dataframe avec les 2 premières lignes. Idem avec df.tail(2) pour les deux dernières.
- df.head(), df.tail() : les 5 premières ou les 5 dernières.
- df.columns : les noms des colonnes, par exemple Index(['A', 'B', 'C', 'D'], dtype='object').
- df.index : les noms des lignes (individus), par exemple Index(['a1', 'a2', 'a3'], dtype='object').
- df.describe() : renvoie un dataframe donnant des statistiques sur les valeurs (nombres de valeurs, moyenne, écart-type, ...), mais uniquement sur les colonnes numériques (faire df.describe(include = 'all') pour avoir toutes les colonnes)

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a1 to a3
Data columns (total 4 columns):
A    3 non-null float64
B    3 non-null float64
C    3 non-null float64
D    3 non-null float64
dtypes: float64(4)
memory usage: 120.0+ bytes

In [10]:
df1.head()

      A     B    C     D
a1  1.1   2.0  3.3   4.0
a2  2.7  10.0  5.4   7.0
a3  5.3   9.0  1.5  15.0

- chargement du fichier
- df2 est le nom de l'objet de type data frame créé
- sep spécifie le caractère séparateur de colonnes
- header = 0 : la ligne numéro 0 = aux noms des champs

In [40]:
import os
os.chdir("F:/___mes données 2022_ok/____mes donnees/_______________________________________________python 3 eme SRSC ESTEM/___pandas GSRI SRSCI")
df2 = pandas.read_table("heart.txt",sep = '\t',header=0)

C:\Users\nouh\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [41]:
print(df2.describe())

              age    pression   cholester    taux_max  depression         pic
count  270.000000  270.000000  270.000000  270.000000  270.000000  270.000000
mean    54.429630  131.344444  249.659259  149.677778   10.500000    1.585185
std      9.102915   17.861608   51.686237   23.165717   11.452098    0.614390
min     29.000000   94.000000  126.000000   71.000000    0.000000    1.000000
25%     48.000000  120.000000  213.000000  133.000000    0.000000    1.000000
50%     55.000000  130.000000  245.000000  153.500000    8.000000    2.000000
75%     61.000000  140.000000  280.000000  166.000000   16.000000    2.000000
max     77.000000  200.000000  564.000000  202.000000   62.000000    3.000000

In [63]:
df2 = pandas.read_table("heart.txt",sep = '\t',header =0)

C:\Users\nouh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

In [42]:
df2

,age,sexe,type_douleur,pression,cholester,sucre,electro,taux_max,angine,depression,pic,vaisseau,coeur
0,69,feminin,D,130,322,A,C,109,non,24,2,D,presence
1,67,feminin,,115,564,A,C,160,non,16,2,A,absence
2,57,masculin,B,124,261,A,A,141,non,3,1,A,presence
3,64,masculin,D,128,263,A,A,105,oui,2,2,B,absence
4,74,feminin,,120,269,A,C,121,oui,2,1,B,absence
5,65,masculin,D,120,177,A,A,140,non,4,1,A,absence
6,56,masculin,C,130,256,B,C,142,oui,6,2,B,presence
7,59,masculin,D,110,239,A,C,142,oui,12,2,B,presence
8,60,masculin,D,140,293,A,C,170,non,12,2,C,presence
9,63,feminin,,150,407,A,C,154,non,40,2,D,presence
10,59,masculin,D,135,234,A,A,161,non,5,2,A,absence
11,53,masculin,D,142,226,A,C,111,oui,0,1,A,absence
12,44,masculin,C,140,235,A,C,180,non,0,1,A,absence
13,61,masculin,A,134,234,A,A,145,non,26,2,C,presence
14,57,feminin,,128,303,A,C,159,non,0,1,B,absence
15,71,feminin,,112,149,A,A,125,non,16,2,A,absence
16,46,masculin,D,140,311,A,A,120,oui,18,2,C,presence
17,53,masculin,D,140,203,B,C,155,oui,31,3,A,presence
18,64,masculin,A,110,211,A,C,144,oui,18,2,A,absence
19,40,masculin,A,140,199,A,A,178,oui,14,1,A,absence
20,67,masculin,D,120,229,A,C,129,oui,26,2,C,presence
21,48,masculin,B,130,245,A,C,180,non,2,2,A,absence
22,43,masculin,D,115,303,A,A,181,non,12,2,A,absence
23,47,masculin,D,112,204,A,A,143,non,1,1,A,absence
24,54,feminin,,132,288,B,C,159,oui,0,1,B,absence
25,48,feminin,,130,275,A,A,139,non,2,1,A,absence
26,46,feminin,,138,243,A,C,152,oui,0,2,A,absence
27,51,feminin,,120,295,A,C,157,non,6,1,A,absence
28,58,masculin,C,112,230,A,C,165,non,25,2,B,presence
29,71,feminin,,110,265,B,C,130,non,0,1,B,absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,68,masculin,C,180,274,B,C,150,oui,16,2,A,presence
241,39,masculin,C,140,321,A,C,182,non,0,1,A,absence
242,53,feminin,,130,264,A,C,143,non,4,2,A,absence
243,62,feminin,,140,268,A,C,160,non,36,3,C,presence
244,51,feminin,,140,308,A,C,142,non,15,1,B,absence
245,60,masculin,D,130,253,A,A,144,oui,14,1,B,presence
246,65,masculin,D,110,248,A,C,158,non,6,1,C,presence
247,65,feminin,,155,269,A,A,148,non,8,1,A,absence
248,60,masculin,C,140,185,A,C,155,non,30,2,A,presence
249,60,masculin,D,145,282,A,C,142,oui,28,2,C,presence
250,54,masculin,D,120,188,A,A,113,non,14,2,B,presence
251,44,masculin,B,130,219,A,C,188,non,0,1,A,absence
252,44,masculin,D,112,290,A,C,153,non,0,1,B,presence
253,51,masculin,C,110,175,A,A,123,non,6,1,A,absence
254,59,masculin,C,150,212,B,A,157,non,16,1,A,absence
255,71,feminin,,160,302,A,A,162,non,4,1,C,absence
256,61,masculin,C,150,243,B,A,137,oui,10,2,A,absence
257,55,masculin,D,132,353,A,A,132,oui,12,2,B,presence
258,64,masculin,C,140,335,A,A,158,non,0,1,A,presence
259,43,masculin,D,150,247,A,A,171,non,15,1,A,absence
260,58,feminin,,120,340,A,A,172,non,0,1,A,absence
261,60,masculin,D,130,206,A,C,132,oui,24,2,C,presence
262,58,masculin,B,120,284,A,C,160,non,18,2,A,presence
263,49,masculin,B,130,266,A,A,171,non,6,1,A,absence
264,48,masculin,B,110,229,A,A,168,non,10,3,A,presence
265,52,masculin,C,172,199,B,A,162,non,5,1,A,absence
266,44,masculin,B,120,263,A,A,173,non,0,1,A,absence
267,56,feminin,,140,294,A,C,153,non,13,2,A,absence
268,57,masculin,D,140,192,A,A,148,non,4,2,A,absence
269,67,masculin,D,160,286,A,C,108,oui,15,2,D,presence

In [43]:
df2.head(2)

,age,sexe,type_douleur,pression,cholester,sucre,electro,taux_max,angine,depression,pic,vaisseau,coeur
0,69,feminin,D,130,322,A,C,109,non,24,2,D,presence
1,67,feminin,,115,564,A,C,160,non,16,2,A,absence

In [44]:
df2.head()

,age,sexe,type_douleur,pression,cholester,sucre,electro,taux_max,angine,depression,pic,vaisseau,coeur
0,69,feminin,D,130,322,A,C,109,non,24,2,D,presence
1,67,feminin,,115,564,A,C,160,non,16,2,A,absence
2,57,masculin,B,124,261,A,A,141,non,3,1,A,presence
3,64,masculin,D,128,263,A,A,105,oui,2,2,B,absence
4,74,feminin,,120,269,A,C,121,oui,2,1,B,absence

In [45]:
df2.tail()

,age,sexe,type_douleur,pression,cholester,sucre,electro,taux_max,angine,depression,pic,vaisseau,coeur
265,52,masculin,C,172,199,B,A,162,non,5,1,A,absence
266,44,masculin,B,120,263,A,A,173,non,0,1,A,absence
267,56,feminin,,140,294,A,C,153,non,13,2,A,absence
268,57,masculin,D,140,192,A,A,148,non,4,2,A,absence
269,67,masculin,D,160,286,A,C,108,oui,15,2,D,presence

In [46]:
df2.tail()

,age,sexe,type_douleur,pression,cholester,sucre,electro,taux_max,angine,depression,pic,vaisseau,coeur
265,52,masculin,C,172,199,B,A,162,non,5,1,A,absence
266,44,masculin,B,120,263,A,A,173,non,0,1,A,absence
267,56,feminin,,140,294,A,C,153,non,13,2,A,absence
268,57,masculin,D,140,192,A,A,148,non,4,2,A,absence
269,67,masculin,D,160,286,A,C,108,oui,15,2,D,presence

In [47]:
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 13 columns):
age             270 non-null int64
sexe            270 non-null object
type_douleur    270 non-null object
pression        270 non-null int64
cholester       270 non-null int64
sucre           270 non-null object
electro         270 non-null object
taux_max        270 non-null int64
angine          270 non-null object
depression      270 non-null int64
pic             270 non-null int64
vaisseau        270 non-null object
coeur           270 non-null object
dtypes: int64(6), object(7)
memory usage: 27.5+ KB
None

In [48]:
df2.describe()

              age    pression   cholester    taux_max  depression         pic
count  270.000000  270.000000  270.000000  270.000000  270.000000  270.000000
mean    54.429630  131.344444  249.659259  149.677778   10.500000    1.585185
std      9.102915   17.861608   51.686237   23.165717   11.452098    0.614390
min     29.000000   94.000000  126.000000   71.000000    0.000000    1.000000
25%     48.000000  120.000000  213.000000  133.000000    0.000000    1.000000
50%     55.000000  130.000000  245.000000  153.500000    8.000000    2.000000
75%     61.000000  140.000000  280.000000  166.000000   16.000000    2.000000
max     77.000000  200.000000  564.000000  202.000000   62.000000    3.000000

In [49]:
#accès à une colonne
print(df2[['sexe']]) # ou bien print(df2.sucre)
#print(df2.sucre)

         sexe
0     feminin
1     feminin
2    masculin
3    masculin
4     feminin
5    masculin
6    masculin
7    masculin
8    masculin
9     feminin
10   masculin
11   masculin
12   masculin
13   masculin
14    feminin
15    feminin
16   masculin
17   masculin
18   masculin
19   masculin
20   masculin
21   masculin
22   masculin
23   masculin
24    feminin
25    feminin
26    feminin
27    feminin
28   masculin
29    feminin
..        ...
240  masculin
241  masculin
242   feminin
243   feminin
244   feminin
245  masculin
246  masculin
247   feminin
248  masculin
249  masculin
250  masculin
251  masculin
252  masculin
253  masculin
254  masculin
255   feminin
256  masculin
257  masculin
258  masculin
259  masculin
260   feminin
261  masculin
262  masculin
263  masculin
264  masculin
265  masculin
266  masculin
267   feminin
268  masculin
269  masculin

[270 rows x 1 columns]

In [53]:
print(df2[['sexe','electro','taux_max','angine']].tail(10))

         sexe electro  taux_max angine
260   feminin       A       172    non
261  masculin       C       132    oui
262  masculin       C       160    non
263  masculin       A       171    non
264  masculin       A       168    non
265  masculin       A       162    non
266  masculin       A       173    non
267   feminin       C       153    non
268  masculin       A       148    non
269  masculin       C       108    oui

In [27]:
#affichage des dernières valeurs
print(df2['age'].tail())

265    52
266    44
267    56
268    57
269    67
Name: age, dtype: int64

In [29]:
#affichage des premières valeurs
print(df2['age'].head())

0    70
1    67
2    57
3    64
4    74
Name: age, dtype: int64

In [30]:
#calculer explicitement la moyenne
print(df2['age'].mean())

54.43333333333333

In [31]:
print(df2['age'].describe())

count    270.000000
mean      54.433333
std        9.109067
min       29.000000
25%       48.000000
50%       55.000000
75%       61.000000
max       77.000000
Name: age, dtype: float64

In [64]:
#un type Series est un vecteur, il est possible d'utiliser des indices
#première valeur
print(df2['age'][0])

70

In [33]:
#un type Series est un vecteur, il est possible d'utiliser des indices
#première valeur
print(df2['age'][0:3])

0    70
1    67
2    57
Name: age, dtype: int64

In [56]:
df2 = pandas.read_table("heart.txt",sep = '\t',header=0)
A=df2.tail(4)
print(A)

     age      sexe type_douleur  pression  cholester sucre electro  taux_max  \
266   44  masculin            B       120        263     A       A       173
267   56   feminin                    140        294     A       C       153
268   17  masculin            D       140        192     A       A       148
269   27  masculin            D       160        286     A       C       108

    angine  depression  pic vaisseau     coeur
266    non           0    1        A   absence
267    non          13    2        A   absence
268    non           4    2        A   absence
269    oui          15    2        D  presence

C:\Users\nouh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.

In [58]:
#trier les valeurs d'une variable de manière croissante
print(A['age'].sort_values())

268    17
269    27
266    44
267    56
Name: age, dtype: int64

## Accès indicé aux données d'un DataFrame
On peut accéder aux valeurs du DataFrame via des indices ou plages d'indice. La structure se comporte alors comme une
matrice. La cellule en haut et à gauche est de coordonnées (0,0).
Il y a différentes manières de le faire, l'utilisation de .iloc[,] constitue une des solutions les plus simples. N'oublions pas
que Shape permet d'obtenir les dimensions (lignes et colonnes) du DataFrame.

In [62]:
#accès à la valeur située en (0,0)
print(df2.iloc[0,0])

59

In [37]:
#valeur située en dernière ligne, première colonne
#utilisation de l'indiçage négatif
print(df2.iloc[-1,0])

67

In [38]:
#5 premières valeurs de toutes les colonnes
#lignes => 0:5 (0 à 5 [non inclus])
#colonnes = : (toutes les colonnes)
print(df2.iloc[0:5,:])

   age      sexe type_douleur  pression  cholester sucre electro  taux_max  \
0   70  masculin            D       130        322     A       C       109
1   67   feminin                    115        564     A       C       160
2   57  masculin            B       124        261     A       A       141
3   64  masculin            D       128        263     A       A       105
4   74   feminin                    120        269     A       C       121

  angine  depression  pic vaisseau     coeur
0    non          24    2        D  presence
1    non          16    2        A   absence
2    non           3    1        A  presence
3    oui           2    2        B   absence
4    oui           2    1        B   absence

In [39]:
#5 premières valeurs des colonnes 2,3,4,5
#lignes => 0:5 (0 à 5 [non inclus])
#colonnes = 2,3,4,5
print(df2.iloc[0:5,2:6])

  type_douleur  pression  cholester sucre
0            D       130        322     A
1                    115        564     A
2            B       124        261     A
3            D       128        263     A
4                    120        269     A

In [55]:
#avec l'indiçage négatif, on peut facilement accéder aux 5 dernières lignes
print(df2.iloc[-5:,:])

     age      sexe type_douleur  pression  cholester sucre electro  taux_max  \
265   52  masculin            C       172        199     B       A       162
266   44  masculin            B       120        263     A       A       173
267   56   feminin                    140        294     A       C       153
268   57  masculin            D       140        192     A       A       148
269   67  masculin            D       160        286     A       C       108

    angine  depression  pic vaisseau     coeur
265    non           5    1        A   absence
266    non           0    1        A   absence
267    non          13    2        A   absence
268    non           4    2        A   absence
269    oui          15    2        D  presence

In [40]:
#5 premières lignes et colonnes 0, 1 et 4
#on a une liste d'indices en colonne
print(df2.iloc[0:5,[0,2,4]])

   age type_douleur  cholester
0   70            D        322
1   67                     564
2   57            B        261
3   64            D        263
4   74                     269

In [41]:
#ou encore, pour exactement la même chose
#remarquez le rôle de 2 dans 0:5:2
print(df2.iloc[0:5,0:5:2])

   age type_douleur  cholester
0   70            D        322
1   67                     564
2   57            B        261
3   64            D        263
4   74                     269

# Restrictions avec les conditions - Les requêtes
Nous pouvons isoler les sous-ensembles d'observations répondant à des critères définis sur les champs. Nous utiliserons
préférentiellement la méthode .loc[,] dans ce cadre.

In [69]:
#liste des individus présentant une douleur de type A
print(df2.loc[df2['type_douleur']=="A",:])

     age      sexe type_douleur  pression  cholester sucre electro  taux_max  \
13    61  masculin            A       134        234     A       A       145
18    64  masculin            A       110        211     A       C       144
19    40  masculin            A       140        199     A       A       178
37    59  masculin            A       160        273     A       C       125
64    63  masculin            A       145        233     B       C       150
85    42  masculin            A       148        244     A       C       178
87    59  masculin            A       178        270     A       C       145
143   51  masculin            A       125        213     A       C       125
158   56  masculin            A       120        193     A       C       162
160   38  masculin            A       120        231     A       A       182
169   65  masculin            A       138        282     B       C       174
170   69  masculin            A       160        234     B       C       131
174   34  masculin            A       118        182     A       C       174
205   52  masculin            A       152        298     B       A       178
210   59  masculin            A       170        288     A       C       159
229   52  masculin            A       118        186     A       C       190

    angine  depression  pic vaisseau     coeur
13     non          26    2        C  presence
18     oui          18    2        A   absence
19     oui          14    1        A   absence
37     non           0    1        A  presence
64     non          23    3        A   absence
85     non           8    1        C   absence
87     non          42    3        A   absence
143    oui          14    1        B   absence
158    non          19    2        A   absence
160    oui          38    2        A  presence
169    non          14    2        B  presence
170    non           1    2        B   absence
174    non           0    1        A   absence
205    non          12    2        A   absence
210    non           2    2        A  presence
229    non           0    2        A   absence

In [70]:
print((df2['type_douleur']=="A").value_counts())

False    254
True      16
Name: type_douleur, dtype: int64

In [71]:
print(df2.loc[df2['type_douleur']!="A",:])

     age      sexe type_douleur  pression  cholester sucre electro  taux_max  \
0     70   feminin            D       130        322     A       C       109
1     67   feminin                    115        564     A       C       160
2     57  masculin            B       124        261     A       A       141
3     64  masculin            D       128        263     A       A       105
4     74   feminin                    120        269     A       C       121
5     65  masculin            D       120        177     A       A       140
6     56  masculin            C       130        256     B       C       142
7     59  masculin            D       110        239     A       C       142
8     60  masculin            D       140        293     A       C       170
9     63   feminin                    150        407     A       C       154
10    59  masculin            D       135        234     A       A       161
11    53  masculin            D       142        226     A       C       111
12    44  masculin            C       140        235     A       C       180
14    57   feminin                    128        303     A       C       159
15    71   feminin                    112        149     A       A       125
16    46  masculin            D       140        311     A       A       120
17    53  masculin            D       140        203     B       C       155
20    67  masculin            D       120        229     A       C       129
21    48  masculin            B       130        245     A       C       180
22    43  masculin            D       115        303     A       A       181
23    47  masculin            D       112        204     A       A       143
24    54   feminin                    132        288     B       C       159
25    48   feminin                    130        275     A       A       139
26    46   feminin                    138        243     A       C       152
27    51   feminin                    120        295     A       C       157
28    58  masculin            C       112        230     A       C       165
29    71   feminin                    110        265     B       C       130
30    57  masculin            C       128        229     A       C       150
31    66  masculin            D       160        228     A       C       138
32    37   feminin                    120        215     A       A       170
..   ...       ...          ...       ...        ...   ...     ...       ...
240   68  masculin            C       180        274     B       C       150
241   39  masculin            C       140        321     A       C       182
242   53   feminin                    130        264     A       C       143
243   62   feminin                    140        268     A       C       160
244   51   feminin                    140        308     A       C       142
245   60  masculin            D       130        253     A       A       144
246   65  masculin            D       110        248     A       C       158
247   65   feminin                    155        269     A       A       148
248   60  masculin            C       140        185     A       C       155
249   60  masculin            D       145        282     A       C       142
250   54  masculin            D       120        188     A       A       113
251   44  masculin            B       130        219     A       C       188
252   44  masculin            D       112        290     A       C       153
253   51  masculin            C       110        175     A       A       123
254   59  masculin            C       150        212     B       A       157
255   71   feminin                    160        302     A       A       162
256   61  masculin            C       150        243     B       A       137
257   55  masculin            D       132        353     A       A       132
258   64  masculin            C       140        335     A       A       158
259   43  masculin            D       150        247     A       A       171
260   58   feminin                    120        340     A       A       172
261   60  masculin            D       130        206     A       C       132
262   58  masculin            B       120        284     A       C       160
263   49  masculin            B       130        266     A       A       171
264   48  masculin            B       110        229     A       A       168
265   52  masculin            C       172        199     B       A       162
266   44  masculin            B       120        263     A       A       173
267   56   feminin                    140        294     A       C       153
268   17  masculin            D       140        192     A       A       148
269   27  masculin            D       160        286     A       C       108

    angine  depression  pic vaisseau     coeur
0      non          24    2        D  presence
1      non          16    2        A   absence
2      non           3    1        A  presence
3      oui           2    2        B   absence
4      oui           2    1        B   absence
5      non           4    1        A   absence
6      oui           6    2        B  presence
7      oui          12    2        B  presence
8      non          12    2        C  presence
9      non          40    2        D  presence
10     non           5    2        A   absence
11     oui           0    1        A   absence
12     non           0    1        A   absence
14     non           0    1        B   absence
15     non          16    2        A   absence
16     oui          18    2        C  presence
17     oui          31    3        A  presence
20     oui          26    2        C  presence
21     non           2    2        A   absence
22     non          12    2        A   absence
23     non           1    1        A   absence
24     oui           0    1        B   absence
25     non           2    1        A   absence
26     oui           0    2        A   absence
27     non           6    1        A   absence
28     non          25    2        B  presence
29     non           0    1        B   absence
30     non           4    2        B  presence
31     non          23    1        A   absence
32     non           0    1        A   absence
..     ...         ...  ...      ...       ...
240    oui          16    2        A  presence
241    non           0    1        A   absence
242    non           4    2        A   absence
243    non          36    3        C  presence
244    non          15    1        B   absence
245    oui          14    1        B  presence
246    non           6    1        C  presence
247    non           8    1        A   absence
248    non          30    2        A  presence
249    oui          28    2        C  presence
250    non          14    2        B  presence
251    non           0    1        A   absence
252    non           0    1        B  presence
253    non           6    1        A   absence
254    non          16    1        A   absence
255    non           4    1        C   absence
256    oui          10    2        A   absence
257    oui          12    2        B  presence
258    non           0    1        A  presence
259    non          15    1        A   absence
260    non           0    1        A   absence
261    oui          24    2        C  presence
262    non          18    2        A  presence
263    non           6    1        A   absence
264    non          10    3        A  presence
265    non           5    1        A   absence
266    non           0    1        A   absence
267    non          13    2        A   absence
268    non           4    2        A   absence
269    oui          15    2        D  presence

[254 rows x 13 columns]

In [72]:
#pour un ensemble de valeurs de la même variable,
#nous utilisons isin()
print(df2.loc[df2['type_douleur'].isin(['A','B']),:])

     age      sexe type_douleur  pression  cholester sucre electro  taux_max  \
2     57  masculin            B       124        261     A       A       141
13    61  masculin            A       134        234     A       A       145
18    64  masculin            A       110        211     A       C       144
19    40  masculin            A       140        199     A       A       178
21    48  masculin            B       130        245     A       C       180
37    59  masculin            A       160        273     A       C       125
43    46  masculin            B       101        197     B       A       156
48    66  masculin            B       160        246     A       A       120
51    52  masculin            B       128        205     B       A       184
59    62  masculin            B       120        281     A       C       103
64    63  masculin            A       145        233     B       C       150
72    70  masculin            B       156        245     A       C       143
79    56  masculin            B       120        236     A       A       178
85    42  masculin            A       148        244     A       C       178
86    62  masculin            B       128        208     B       C       140
87    59  masculin            A       178        270     A       C       145
90    59  masculin            B       140        221     A       A       164
111   41  masculin            B       110        235     A       A       153
114   42  masculin            B       120        295     A       A       162
128   52  masculin            B       134        201     A       A       158
143   51  masculin            A       125        213     A       C       125
144   54  masculin            B       192        283     A       C       195
157   45  masculin            B       128        308     A       C       170
158   56  masculin            A       120        193     A       C       162
160   38  masculin            A       120        231     A       A       182
162   55  masculin            B       130        262     A       A       155
169   65  masculin            A       138        282     B       C       174
170   69  masculin            A       160        234     B       C       131
174   34  masculin            A       118        182     A       C       174
192   54  masculin            B       108        309     A       A       156
205   52  masculin            A       152        298     B       A       178
210   59  masculin            A       170        288     A       C       159
214   29  masculin            B       130        204     A       C       202
219   44  masculin            B       120        220     A       A       170
225   41  masculin            B       135        203     A       A       132
229   52  masculin            A       118        186     A       C       190
239   52  masculin            B       120        325     A       A       172
251   44  masculin            B       130        219     A       C       188
262   58  masculin            B       120        284     A       C       160
263   49  masculin            B       130        266     A       A       171
264   48  masculin            B       110        229     A       A       168
266   44  masculin            B       120        263     A       A       173

    angine  depression  pic vaisseau     coeur
2      non           3    1        A  presence
13     non          26    2        C  presence
18     oui          18    2        A   absence
19     oui          14    1        A   absence
21     non           2    2        A   absence
37     non           0    1        A  presence
43     non           0    1        A   absence
48     oui           0    2        D  presence
51     non           0    1        A   absence
59     non          14    2        B  presence
64     non          23    3        A   absence
72     non           0    1        A   absence
79     non           8    1        A   absence
85     non           8    1        C   absence
86     non           0    1        A   absence
87     non          42    3        A   absence
90     oui           0    1        A   absence
111    non           0    1        A   absence
114    non           0    1        A   absence
128    non           8    1        B   absence
143    oui          14    1        B   absence
144    non           0    1        B  presence
157    non           0    1        A   absence
158    non          19    2        A   absence
160    oui          38    2        A  presence
162    non           0    1        A   absence
169    non          14    2        B  presence
170    non           1    2        B   absence
174    non           0    1        A   absence
192    non           0    1        A   absence
205    non          12    2        A   absence
210    non           2    2        A  presence
214    non           0    1        A   absence
219    non           0    1        A   absence
225    non           0    2        A   absence
229    non           0    2        A   absence
239    non           2    1        A   absence
251    non           0    1        A   absence
262    non          18    2        A  presence
263    non           6    1        A   absence
264    non          10    3        A  presence
266    non           0    1        A   absence

In [75]:
#Des opérateurs logiques permettent de combiner les conditions. 
#Nous utilisons respectivement : & pour ET, | pour OU, et ~ pour la négation.
#liste des individus présentant une douleur de type A et angine == oui
print(df2.loc[(df2['type_douleur']=="A") & (df2['angine'] == "oui"),:])

     age      sexe type_douleur  pression  cholester sucre electro  taux_max  \
18    64  masculin            A       110        211     A       C       144
19    40  masculin            A       140        199     A       A       178
143   51  masculin            A       125        213     A       C       125
160   38  masculin            A       120        231     A       A       182

    angine  depression  pic vaisseau     coeur
18     oui          18    2        A   absence
19     oui          14    1        A   absence
143    oui          14    1        B   absence
160    oui          38    2        A  presence

In [49]:
#liste des personnes de moins de 45 ans, de sexe masculin, présentant une
#maladie cardiaque
print(df2.loc[(df2['age'] < 45) & (df2['sexe'] == "masculin") & (df2['coeur'] == "presence"),:])

     age      sexe type_douleur  pression  cholester sucre electro  taux_max  \
40    40  masculin            D       152        223     A       A       181
47    44  masculin            D       110        197     A       C       177
50    42  masculin            D       136        315     A       A       125
81    35  masculin            D       120        198     A       A       130
147   40  masculin            D       110        167     A       C       114
160   38  masculin            A       120        231     A       A       182
182   41  masculin            D       110        172     A       C       158
193   35  masculin            D       126        282     A       C       156
231   39  masculin            D       118        219     A       A       140
237   43  masculin            D       120        177     A       C       120
252   44  masculin            D       112        290     A       C       153

    angine  depression  pic vaisseau     coeur
40     non           0    1        A  presence
47     non           0    1        B  presence
50     oui          18    2        A  presence
81     oui          16    2        A  presence
147    oui          20    2        A  presence
160    oui          38    2        A  presence
182    non           0    1        A  presence
193    oui           0    1        A  presence
231    non          12    2        A  presence
237    oui          25    2        A  presence
252    non           0    1        B  presence

In [76]:
import os
donnees=pandas.read_csv("heart.csv")

In [77]:
donnees

    age;sexe;type_douleur;pression;cholester;sucre;electro;taux_max;angine;depression;pic;vaisseau;coeur
0    70;masculin;D;130;322;A;C;109;non;24;2;D;presence
1      67;feminin; ;115;564;A;C;160;non;16;2;A;absence
2     57;masculin;B;124;261;A;A;141;non;3;1;A;presence
3      64;masculin;D;128;263;A;A;105;oui;2;2;B;absence
4       74;feminin; ;120;269;A;C;121;oui;2;1;B;absence
5      65;masculin;D;120;177;A;A;140;non;4;1;A;absence
6     56;masculin;C;130;256;B;C;142;oui;6;2;B;presence
7    59;masculin;D;110;239;A;C;142;oui;12;2;B;presence
8    60;masculin;D;140;293;A;C;170;non;12;2;C;presence
9     63;feminin; ;150;407;A;C;154;non;40;2;D;presence
10     59;masculin;D;135;234;A;A;161;non;5;2;A;absence
11     53;masculin;D;142;226;A;C;111;oui;0;1;A;absence
12     44;masculin;C;140;235;A;C;180;non;0;1;A;absence
13   61;masculin;A;134;234;A;A;145;non;26;2;C;presence
14      57;feminin; ;128;303;A;C;159;non;0;1;B;absence
15     71;feminin; ;112;149;A;A;125;non;16;2;A;absence
16   46;masculin;D;140;311;A;A;120;oui;18;2;C;presence
17   53;masculin;D;140;203;B;C;155;oui;31;3;A;presence
18    64;masculin;A;110;211;A;C;144;oui;18;2;A;absence
19    40;masculin;A;140;199;A;A;178;oui;14;1;A;absence
20   67;masculin;D;120;229;A;C;129;oui;26;2;C;presence
21     48;masculin;B;130;245;A;C;180;non;2;2;A;absence
22    43;masculin;D;115;303;A;A;181;non;12;2;A;absence
23     47;masculin;D;112;204;A;A;143;non;1;1;A;absence
24      54;feminin; ;132;288;B;C;159;oui;0;1;B;absence
25      48;feminin; ;130;275;A;A;139;non;2;1;A;absence
26      46;feminin; ;138;243;A;C;152;oui;0;2;A;absence
27      51;feminin; ;120;295;A;C;157;non;6;1;A;absence
28   58;masculin;C;112;230;A;C;165;non;25;2;B;presence
29      71;feminin; ;110;265;B;C;130;non;0;1;B;absence
..                                                 ...
240  68;masculin;C;180;274;B;C;150;oui;16;2;A;presence
241    39;masculin;C;140;321;A;C;182;non;0;1;A;absence
242     53;feminin; ;130;264;A;C;143;non;4;2;A;absence
243   62;feminin; ;140;268;A;C;160;non;36;3;C;presence
244    51;feminin; ;140;308;A;C;142;non;15;1;B;absence
245  60;masculin;D;130;253;A;A;144;oui;14;1;B;presence
246   65;masculin;D;110;248;A;C;158;non;6;1;C;presence
247     65;feminin; ;155;269;A;A;148;non;8;1;A;absence
248  60;masculin;C;140;185;A;C;155;non;30;2;A;presence
249  60;masculin;D;145;282;A;C;142;oui;28;2;C;presence
250  54;masculin;D;120;188;A;A;113;non;14;2;B;presence
251    44;masculin;B;130;219;A;C;188;non;0;1;A;absence
252   44;masculin;D;112;290;A;C;153;non;0;1;B;presence
253    51;masculin;C;110;175;A;A;123;non;6;1;A;absence
254   59;masculin;C;150;212;B;A;157;non;16;1;A;absence
255     71;feminin; ;160;302;A;A;162;non;4;1;C;absence
256   61;masculin;C;150;243;B;A;137;oui;10;2;A;absence
257  55;masculin;D;132;353;A;A;132;oui;12;2;B;presence
258   64;masculin;C;140;335;A;A;158;non;0;1;A;presence
259   43;masculin;D;150;247;A;A;171;non;15;1;A;absence
260     58;feminin; ;120;340;A;A;172;non;0;1;A;absence
261  60;masculin;D;130;206;A;C;132;oui;24;2;C;presence
262  58;masculin;B;120;284;A;C;160;non;18;2;A;presence
263    49;masculin;B;130;266;A;A;171;non;6;1;A;absence
264  48;masculin;B;110;229;A;A;168;non;10;3;A;presence
265    52;masculin;C;172;199;B;A;162;non;5;1;A;absence
266    44;masculin;B;120;263;A;A;173;non;0;1;A;absence
267    56;feminin; ;140;294;A;C;153;non;13;2;A;absence
268    57;masculin;D;140;192;A;A;148;non;4;2;A;absence
269  67;masculin;D;160;286;A;C;108;oui;15;2;D;presence

[270 rows x 1 columns]

In [84]:
donnees=pandas.read_csv("heart.csv",sep=';')

In [85]:
donnees

,age,sexe,type_douleur,pression,cholester,sucre,electro,taux_max,angine,depression,pic,vaisseau,coeur
0,70,masculin,D,130,322,A,C,109,non,24,2,D,presence
1,67,feminin,,115,564,A,C,160,non,16,2,A,absence
2,57,masculin,B,124,261,A,A,141,non,3,1,A,presence
3,64,masculin,D,128,263,A,A,105,oui,2,2,B,absence
4,74,feminin,,120,269,A,C,121,oui,2,1,B,absence
5,65,masculin,D,120,177,A,A,140,non,4,1,A,absence
6,56,masculin,C,130,256,B,C,142,oui,6,2,B,presence
7,59,masculin,D,110,239,A,C,142,oui,12,2,B,presence
8,60,masculin,D,140,293,A,C,170,non,12,2,C,presence
9,63,feminin,,150,407,A,C,154,non,40,2,D,presence
10,59,masculin,D,135,234,A,A,161,non,5,2,A,absence
11,53,masculin,D,142,226,A,C,111,oui,0,1,A,absence
12,44,masculin,C,140,235,A,C,180,non,0,1,A,absence
13,61,masculin,A,134,234,A,A,145,non,26,2,C,presence
14,57,feminin,,128,303,A,C,159,non,0,1,B,absence
15,71,feminin,,112,149,A,A,125,non,16,2,A,absence
16,46,masculin,D,140,311,A,A,120,oui,18,2,C,presence
17,53,masculin,D,140,203,B,C,155,oui,31,3,A,presence
18,64,masculin,A,110,211,A,C,144,oui,18,2,A,absence
19,40,masculin,A,140,199,A,A,178,oui,14,1,A,absence
20,67,masculin,D,120,229,A,C,129,oui,26,2,C,presence
21,48,masculin,B,130,245,A,C,180,non,2,2,A,absence
22,43,masculin,D,115,303,A,A,181,non,12,2,A,absence
23,47,masculin,D,112,204,A,A,143,non,1,1,A,absence
24,54,feminin,,132,288,B,C,159,oui,0,1,B,absence
25,48,feminin,,130,275,A,A,139,non,2,1,A,absence
26,46,feminin,,138,243,A,C,152,oui,0,2,A,absence
27,51,feminin,,120,295,A,C,157,non,6,1,A,absence
28,58,masculin,C,112,230,A,C,165,non,25,2,B,presence
29,71,feminin,,110,265,B,C,130,non,0,1,B,absence
...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,68,masculin,C,180,274,B,C,150,oui,16,2,A,presence
241,39,masculin,C,140,321,A,C,182,non,0,1,A,absence
242,53,feminin,,130,264,A,C,143,non,4,2,A,absence
243,62,feminin,,140,268,A,C,160,non,36,3,C,presence
244,51,feminin,,140,308,A,C,142,non,15,1,B,absence
245,60,masculin,D,130,253,A,A,144,oui,14,1,B,presence
246,65,masculin,D,110,248,A,C,158,non,6,1,C,presence
247,65,feminin,,155,269,A,A,148,non,8,1,A,absence
248,60,masculin,C,140,185,A,C,155,non,30,2,A,presence
249,60,masculin,D,145,282,A,C,142,oui,28,2,C,presence
250,54,masculin,D,120,188,A,A,113,non,14,2,B,presence
251,44,masculin,B,130,219,A,C,188,non,0,1,A,absence
252,44,masculin,D,112,290,A,C,153,non,0,1,B,presence
253,51,masculin,C,110,175,A,A,123,non,6,1,A,absence
254,59,masculin,C,150,212,B,A,157,non,16,1,A,absence
255,71,feminin,,160,302,A,A,162,non,4,1,C,absence
256,61,masculin,C,150,243,B,A,137,oui,10,2,A,absence
257,55,masculin,D,132,353,A,A,132,oui,12,2,B,presence
258,64,masculin,C,140,335,A,A,158,non,0,1,A,presence
259,43,masculin,D,150,247,A,A,171,non,15,1,A,absence
260,58,feminin,,120,340,A,A,172,non,0,1,A,absence
261,60,masculin,D,130,206,A,C,132,oui,24,2,C,presence
262,58,masculin,B,120,284,A,C,160,non,18,2,A,presence
263,49,masculin,B,130,266,A,A,171,non,6,1,A,absence
264,48,masculin,B,110,229,A,A,168,non,10,3,A,presence
265,52,masculin,C,172,199,B,A,162,non,5,1,A,absence
266,44,masculin,B,120,263,A,A,173,non,0,1,A,absence
267,56,feminin,,140,294,A,C,153,non,13,2,A,absence
268,57,masculin,D,140,192,A,A,148,non,4,2,A,absence
269,67,masculin,D,160,286,A,C,108,oui,15,2,D,presence

In [73]:
donnees[['type_douleur',  'pression']]

    type_douleur  pression
0              D       130
1                      115
2              B       124
3              D       128
4                      120
..           ...       ...
265            C       172
266            B       120
267                    140
268            D       140
269            D       160

[270 rows x 2 columns]

In [74]:
print(donnees.iloc[0:5,0:5:2])

   age type_douleur  cholester
0   70            D        322
1   67                     564
2   57            B        261
3   64            D        263
4   74                     269